### ISSUE TITLE
add exampleSite with initial setup

### ISSUE THREAD

**Issue by mipmip** [chaoming/hugo-saasify-theme#1]
This helps new users.

**Comment by chaoming** [comment]
Thanks for the feedback. The demo site including Github Action to deploy to Github Pages is here: https://github.com/chaoming/hugo-saasify-demo

I am new to building themes. Let me see if I can merge the two repos into one. If you have some guides I can read that would be very helpful.

**Comment by chaoming** [comment]
Added the exampleSite in this commit 3a570e36d962fd46eae1b22dbcc308dc3f62eab0
